### ISSUE TITLE
Not loading ENV variable for NGINX API_KEY

### ISSUE THREAD

**Issue by kellerfabian** [WeLytics/ByteBuoy#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Web API

### Describe the bug

Proxy Docker container with nginx image is not consuming the provided API-Key

### Steps to reproduce

using docker-compose.yml instruction:

```yml
  proxy:
    build: ./client/ByteBuoy.ProxyNginx/
    ports:
      - "8080:80"
    environment:
      - API_KEY=bb_JIIHHAA
      - API_SERVICE_URL=http://api:5000  
```

and using Dockerfile instructions

```bash
FROM nginx:latest

ENV API_KEY=XXXXX

COPY nginx.conf /etc/nginx/nginx.conf
#conf.d/default.conf

COPY default.conf.template /etc/nginx/templates/default.conf.template
#CMD /bin/bash -c "envsubst '$${API_KEY}' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
# Command to run when the container starts
CMD /bin/bash -c "envsubst '$${API_KEY}' < /etc/nginx/templates/default.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"


# CMD nginx -g 'daemon off;'

```

### Relevant log output

```shell
bytebuoy-proxy-1  | 2024/01/27 23:39:08 [emerg] 7#7: unknown "api_key" variable
bytebuoy-proxy-1  | nginx: [emerg] unknown "api_key" variable
```

### Version

0.0.1
